name: github step summary

on:
  workflow_dispatch:


jobs:
  print-step-summary:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: echo hello world
        run: |
          echo "<pre>"  >> $GITHUB_STEP_SUMMARY
          echo "<h3>" >> $GITHUB_STEP_SUMMARY
          echo "Hello World" >> $GITHUB_STEP_SUMMARY
          echo "</h3>" >> $GITHUB_STEP_SUMMARY
          cat sample.html >> $GITHUB_STEP_SUMMARY
          echo "</pre>" >> $GITHUB_STEP_SUMMARY
