name: github step summary

on:
  workflow_dispatch:


jobs:
  print-step-summary:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: echo hello world
        run: |
          echo "Hello World" >> $GITHUB_STEP_SUMMARY
